# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Pyright for Windows
        uses: jakebailey/pyright-action@v1.0.2
        with:
          python-platform: Windows # Analyze for a specific platform (Darwin, Linux, Windows) -- optional
          python-version: 3.6 # Analyze for a specific version (3.3, 3.4, etc.) -- optional
        
      - name: Pyright for Linux
        uses: jakebailey/pyright-action@v1.0.2
        with:
          python-platform: Linux # Analyze for a specific platform (Darwin, Linux, Windows) -- optional
          python-version: 3.6 # Analyze for a specific version (3.3, 3.4, etc.) -- optional
      
      - name: Pyright for Darwin
        uses: jakebailey/pyright-action@v1.0.2
        with:
          python-platform: Darwin # Analyze for a specific platform (Darwin, Linux, Windows) -- optional
          python-version: 3.6 # Analyze for a specific version (3.3, 3.4, etc.) -- optional
